spring.application.name=forohub

# Conexión a Base de Datos usando Variables de Entorno para ocultar datos
spring.datasource.url=jdbc:postgresql://localhost:5432/dbforohub
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

#Validate verifica que Flyway hizo su trabajo
spring.jpa.hibernate.ddl-auto=validate

# Firma secreta de Token
jwt.secret=${JWT_SECRET}